# Site settings
title: Keene Industries
header-img: img/home-bg.jpg
email: brandon@cmdrkeene.net
description: "Your Ad Here"
baseurl: ""
url: "http://blog.cmdrkeene.net"
twitter_username: cmdrkeene
github_username:  cmdrkeene
timezone: America/New_York

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
